/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SanctumRouteImport } from './routes/sanctum'
import { Route as CascadeRouteImport } from './routes/cascade'
import { Route as IndexRouteImport } from './routes/index'

const SanctumRoute = SanctumRouteImport.update({
  id: '/sanctum',
  path: '/sanctum',
  getParentRoute: () => rootRouteImport,
} as any)
const CascadeRoute = CascadeRouteImport.update({
  id: '/cascade',
  path: '/cascade',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cascade': typeof CascadeRoute
  '/sanctum': typeof SanctumRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cascade': typeof CascadeRoute
  '/sanctum': typeof SanctumRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cascade': typeof CascadeRoute
  '/sanctum': typeof SanctumRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cascade' | '/sanctum'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cascade' | '/sanctum'
  id: '__root__' | '/' | '/cascade' | '/sanctum'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CascadeRoute: typeof CascadeRoute
  SanctumRoute: typeof SanctumRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sanctum': {
      id: '/sanctum'
      path: '/sanctum'
      fullPath: '/sanctum'
      preLoaderRoute: typeof SanctumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cascade': {
      id: '/cascade'
      path: '/cascade'
      fullPath: '/cascade'
      preLoaderRoute: typeof CascadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CascadeRoute: CascadeRoute,
  SanctumRoute: SanctumRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
